"""
Pytest configuration and shared fixtures for OpenAPI testing
"""
import pytest
from app import create_app


@pytest.fixture(scope="session")
def openapi_spec_url():
    """
    URL to fetch OpenAPI spec from.
    For local testing, this can be a test client.
    For integration testing, this can be the actual server URL.
    """
    return "http://localhost:5000/api/apispec.json"


@pytest.fixture
def app():
    """Create application for testing"""
    app = create_app('testing')
    with app.app_context():
        yield app


@pytest.fixture
def openapi_spec(app):
    """
    Fetch OpenAPI spec from the test app.
    This ensures we're testing against the actual spec generated by Flasgger.
    """
    with app.test_client() as client:
        response = client.get('/api/apispec.json')
        assert response.status_code == 200
        return response.get_json()

